trailingComma: 'es5'
tabWidth: 2
semi: false
singleQuote: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - 'prettier-plugin-tailwindcss' # MUST come last
importOrder: ['^@', '^[./]']
importOrderSeparation: true
importOrderSortSpecifiers: true
